spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: Testtest123
  jpa:
    hibernate:
      ddl-auto: update


config:
  agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0 CustomBrowser/1.0

#  Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com
  site:
    - url: https://skillbox.ru
      name: skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://www.svetlovka.ru
#      name: Библиотека
    - url: https://et-cetera.ru/mobile/
      name: Театр «Et Cetera»
